sftp_filenames:
  FILENAME_FOR_EDUCATORS_IMPORT:     /home/bedford/data/staff.csv
  FILENAME_FOR_STUDENTS_IMPORT:      /home/bedford/data/student.csv
  FILENAME_FOR_BEHAVIOR_IMPORT:      /home/bedford/data/conduct.csv
  FILENAME_FOR_ATTENDANCE_IMPORT:    /home/bedford/data/attendance.csv
  FILENAME_FOR_ASSESSMENT_IMPORT:    /home/bedford/data/Assessment.csv


school_definitions_for_import:
  - name: Lane Elementary
    local_id: Lane
    school_type: ES
  
  - name: Davis Elementary
    local_id: Davis
    school_type: ES

  
school_definitions_not_yet_used:
  - name: John Glenn Middle School
    local_id: JGMS
    school_type: MS
  
  - name: Bedford High School
    local_id: BHS
    school_type: HS
  
  - name: Pre-K
    local_id: BHS Pre-K
    school_type: ECS
  
  - name: System
    local_id: System
    school_type: OTHER
